pipeline:
  publish:
    image: plugins/docker
    repo: goharbor.erxes.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    registry: goharbor.erxes.io
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-latest
