pipeline:
  build:
    image: node:10.16.0-slim
    commands:
      - yarn install
      - cp .env.sample .env
      - CI="" yarn build
      # https://github.com/facebook/create-react-app/issues/2453
    when:
      branch:
        - demo
      event:
        - push

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - demo
      event:
        - push
